### ISSUE TITLE
Unorthodox way of getting one's attention

### ISSUE THREAD

**Issue by mickeypash** [dholdaway/snapshot#1]
Hey Darren!

It was really hard to find any other way to connect!
You're pretty locked down on LinkedIn and Twitter and your sites don't have any contact info!

Hi my name is Mickey and I'm a software engineer with a thing for DevOps.
Currently working at TouchSurgery 😉 
Was wondering if I could ask you a couple of questions?

Cheers,
Mickey

**Comment by dholdaway** [comment]
Ask Hansel for my email address.

Thanks

D
